// Code generated by goyacc - DO NOT EDIT.

package scl

import __yyfmt__ "fmt"

import (
	"fmt"
)

// Result AST structs
type Statement interface{}

type SetStmt struct {
	Collection string
	Key        string
	Value      string
}

type GetStmt struct {
	Collection string
	Key        string
}

type DeleteStmt struct {
	Collection string
	Key        string
}

type TruncateStmt struct {
	Collection string
}

type DropStmt struct {
	Collection string
	Key        string
}

type UpdateStmt struct {
	Collection string
	Key        string
	Value      string
}

type yySymType struct {
	yys  int
	str  string
	stmt Statement
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault  = 57361
	yyEofCode  = 57344
	BOOL       = 57350
	COLLECTION = 57346
	COLON      = 57358
	DELETE     = 57354
	DOT        = 57360
	DROP       = 57356
	GET        = 57353
	JSON       = 57351
	KEY        = 57347
	NUMBER     = 57349
	SEMICOLON  = 57359
	SET        = 57352
	STRING     = 57348
	TRUNCATE   = 57355
	UPDATE     = 57357
	yyErrCode  = 57345

	yyMaxDepth = 200
	yyTabOfs   = -21
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		57359: 0,  // SEMICOLON (19x)
		57346: 1,  // COLLECTION (6x)
		57362: 2,  // collection (6x)
		57360: 3,  // DOT (5x)
		57347: 4,  // KEY (4x)
		57366: 5,  // key (4x)
		57344: 6,  // $end (3x)
		57358: 7,  // COLON (3x)
		57354: 8,  // DELETE (3x)
		57356: 9,  // DROP (3x)
		57353: 10, // GET (3x)
		57352: 11, // SET (3x)
		57355: 12, // TRUNCATE (3x)
		57357: 13, // UPDATE (3x)
		57350: 14, // BOOL (2x)
		57351: 15, // JSON (2x)
		57349: 16, // NUMBER (2x)
		57348: 17, // STRING (2x)
		57372: 18, // value (2x)
		57363: 19, // delete_stmt (1x)
		57364: 20, // drop_stmt (1x)
		57365: 21, // get_stmt (1x)
		57367: 22, // set_stmt (1x)
		57368: 23, // statement (1x)
		57369: 24, // statements (1x)
		57370: 25, // truncate_stmt (1x)
		57371: 26, // update_stmt (1x)
		57361: 27, // $default (0x)
		57345: 28, // error (0x)
	}

	yySymNames = []string{
		"SEMICOLON",
		"COLLECTION",
		"collection",
		"DOT",
		"KEY",
		"key",
		"$end",
		"COLON",
		"DELETE",
		"DROP",
		"GET",
		"SET",
		"TRUNCATE",
		"UPDATE",
		"BOOL",
		"JSON",
		"NUMBER",
		"STRING",
		"value",
		"delete_stmt",
		"drop_stmt",
		"get_stmt",
		"set_stmt",
		"statement",
		"statements",
		"truncate_stmt",
		"update_stmt",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {24, 0},
		2:  {24, 3},
		3:  {23, 1},
		4:  {23, 1},
		5:  {23, 1},
		6:  {23, 1},
		7:  {23, 1},
		8:  {23, 1},
		9:  {22, 6},
		10: {21, 4},
		11: {19, 4},
		12: {25, 2},
		13: {20, 2},
		14: {26, 6},
		15: {2, 1},
		16: {5, 1},
		17: {18, 1},
		18: {18, 1},
		19: {18, 1},
		20: {18, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [40][]uint8{
		// 0
		{6: 20, 8: 20, 20, 20, 20, 20, 20, 24: 22},
		{6: 21, 8: 32, 34, 31, 30, 33, 35, 19: 26, 28, 25, 24, 23, 25: 27, 29},
		{60},
		{18},
		{17},
		// 5
		{16},
		{15},
		{14},
		{13},
		{1: 37, 55},
		// 10
		{1: 37, 52},
		{1: 37, 49},
		{1: 37, 48},
		{1: 37, 47},
		{1: 37, 36},
		// 15
		{3: 38},
		{6, 3: 6},
		{4: 40, 39},
		{7: 41},
		{5, 7: 5},
		// 20
		{14: 45, 46, 44, 43, 42},
		{7},
		{4},
		{3},
		{2},
		// 25
		{1},
		{8},
		{9},
		{3: 50},
		{4: 40, 51},
		// 30
		{10},
		{3: 53},
		{4: 40, 54},
		{11},
		{3: 56},
		// 35
		{4: 40, 57},
		{7: 58},
		{14: 45, 46, 44, 43, 59},
		{12},
		{6: 19, 8: 19, 19, 19, 19, 19, 19},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 28

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 2:
		{
			stmtType := ""
			switch yyS[yypt-1].stmt.(type) {
			case *SetStmt:
				stmtType = "SET"
			case *GetStmt:
				stmtType = "GET"
			case *DeleteStmt:
				stmtType = "DELETE"
			case *TruncateStmt:
				stmtType = "TRUNCATE"
			case *DropStmt:
				stmtType = "DROP"
			case *UpdateStmt:
				stmtType = "UPDATE"
			}
			err := PrintToStd(yyS[yypt-1].stmt, stmtType)
			if err != nil {
				fmt.Println("Error extracting SCL:", err)
			}
		}
	case 3:
		{
			yyVAL.stmt = yyS[yypt-0].stmt
		}
	case 4:
		{
			yyVAL.stmt = yyS[yypt-0].stmt
		}
	case 5:
		{
			yyVAL.stmt = yyS[yypt-0].stmt
		}
	case 6:
		{
			yyVAL.stmt = yyS[yypt-0].stmt
		}
	case 7:
		{
			yyVAL.stmt = yyS[yypt-0].stmt
		}
	case 8:
		{
			yyVAL.stmt = yyS[yypt-0].stmt
		}
	case 9:
		{
			yyVAL.stmt = &SetStmt{Collection: yyS[yypt-4].str, Key: yyS[yypt-2].str, Value: yyS[yypt-0].str}
		}
	case 10:
		{
			yyVAL.stmt = &GetStmt{Collection: yyS[yypt-2].str, Key: yyS[yypt-0].str}
		}
	case 11:
		{
			yyVAL.stmt = &DeleteStmt{Collection: yyS[yypt-2].str, Key: yyS[yypt-0].str}
		}
	case 12:
		{
			yyVAL.stmt = &TruncateStmt{Collection: yyS[yypt-0].str}
		}
	case 13:
		{
			yyVAL.stmt = &DropStmt{Collection: yyS[yypt-0].str, Key: "*"}
		}
	case 14:
		{
			yyVAL.stmt = &UpdateStmt{Collection: yyS[yypt-4].str, Key: yyS[yypt-2].str, Value: yyS[yypt-0].str}
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
