blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    type: discussion
    url: https://github.com/dalfrom/simplecache/discussions
    about: Discussions, support request or question relating to simplecache